### ISSUE TITLE
Data Stewardship Processes to support with the DSU Data Inventory

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#101]
@dfo-pacific-science/data-stewardship-unit Can we start a discussion here about what processes we'd like to use the DSU data inventory for? 

Features we agree we need: (Edit as we discuss and agree)
- [ ] Feature 1

**Comment by Br-Johnson** [comment]
For example, 
- I think it would be great to be able to track how many data stewards we've supported to get their short-form for the Data Stewardship Initiative submitted to Marisa Ramey / OCDS.

- Ideally, we can also track which data sets have had Data Quality Assessments, and FAIR assessments.

**Comment by AnnaD-M** [comment]
@Br-Johnson issue #67 touches on this, wondering how to consolidate?

**Comment by Br-Johnson** [comment]
My bad. Consolidate to #67! :)
