### ISSUE TITLE
Conduct content audit and gap analysis with Declan Embury re: Pacific Data Hub

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#103]
Declan Embury is working on a [Pacific Data Hub SharePoint website](https://086gc.sharepoint.com/:u:/r/sites/PacificDataHub/SitePages/DataHub.aspx?csf=1&web=1&share=ETFi5Q9__tJJhq4fzudfYusB2ppw_6hIcbqPmODlTWcp9g&e=UGdd7Z) and have a co-op student coming on board to work on it. This site essentially is a refresh/rebrand of the Pacific Region Data Community SharePoint site. 

I would like us to make sure we're coordinated with Declan and not building up content that he is working on. We should come up with a 1-page overview of the purpose and types of content we would like to see on the DSU GitHub website so that we can compare with Declan. If Declan or his student could do the same, this will allow us to audit our content and identify gaps.

**Comment by alburycatalina** [comment]
Hey Brett. I created that 1-pager and am ready to send this over to Declan and ask if he'd like to meet. Do you want to give it a quick review? [Here it is](https://086gc-my.sharepoint.com/:w:/r/personal/catalina_albury_dfo-mpo_gc_ca/Documents/Projects/DSU-website/[DSU-Website-Brief.docx](https://086gc-my.sharepoint.com/:w:/r/personal/catalina_albury_dfo-mpo_gc_ca/Documents/Projects/DSU-website/DSU-Website-Brief.docx?d=w3b868b4772b144f695b004b3e9ae84b8&csf=1&web=1&e=dg7zdj)?d=w3b868b4772b144f695b004b3e9ae84b8&csf=1&web=1&e=dg7zdj)
