### ISSUE TITLE
Email Di Wan to ask about Deployment to DMApps

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#104]
Questions from Albury:
How does hosting there work?
Benefits and limitations
How resources are managed there (are there any restrictions on use? Is there costing?)
Possible alternatives to explore for hosting internally

**Comment by ShaorongDFO** [comment]
I was thinking the same thing, how to utilize the DMApps as the open portal for SPSR? How to get CDOS involved, and is there any funding available? Perhaps we could ask Diana for potential funding and CDOS support?

**Comment by Br-Johnson** [comment]
Diana's goal is to avoid requiring CDOS support. I will be in touch with Di and we can assess the workflow she can offer before looping in Diana

**Comment by Br-Johnson** [comment]
@alburycatalina I emailed Di and she said no documentation exists regarding how to deploy to Water Properties DMApps, and we can set up a meeting with her to learn more.

**Comment by ShaorongDFO** [comment]
Is this the [Water Properties DMApps](https://www.waterproperties.ca/mainlogin.php?refer=/dashboard.php?mode=data)?
