### ISSUE TITLE
Create ERD for SPSR Database

### ISSUE THREAD

**Issue by alburycatalina** [dfo-pacific-science/data-stewardship-unit#114]

**Comment by Br-Johnson** [comment]
Perhaps this is separate from our discussion about ERDs, but I was thinking that an ERD for the SPSR would be nice. All good if this in addition to that :)

**Comment by alburycatalina** [comment]
Yes apologies! Wires were crossed when I titled this issue

**Comment by Br-Johnson** [comment]
Hey Albury nice work getting this one tied off. It looks great. Just one feedback note to say please include a comment to explain how an issue is closed and or a link to outputs when closing issues for future documentation purposes :)

Here's the ERD:

https://miro.com/app/board/uXjVL5bUqUU=/?share_link_id=774675123514
