### ISSUE TITLE
Establish the Pacific Salmon Data Community of Practice.

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#19]
[Here's a link to the Community of Practice Terms of Reference](https://086gc-my.sharepoint.com/:w:/r/personal/brett_johnson_dfo-mpo_gc_ca/Documents/DFO%20Pacific%20Salmon%20Data%20Community%20of%20Practice%20Terms%20of%20Reference.docx?d=w81e456aab23a449c9a2825dfa48513e8&csf=1&web=1&e=8FsI41) I created in the first month or so of starting the job. One of the next steps is to ask Shelee to send out an invite to her list of contacts for a first meeting. We should develop an engagement strategy before that though.

- [x] #24
- [x] #25
- [x] Ask Shelee to send out email to contacts for invite to PSD CoP
- [x] #75
- [x] #97

**Comment by Br-Johnson** [comment]
Given the delays with getting @stfinnis position full time @AnnaD-M I would like you to take the lead on this.

**Comment by Br-Johnson** [comment]
@stfinnis To summarize: Shelee would like us to recommend 2 staff to attend the PSD CoP per Area, Section, or Division (where no section in a particular division has been identified). Shelee will then email each Area Chief, Section Head or Division Manager to get their approval of the two staff we're suggesting.

We can draw upon the staff identified in the Salmon Population WG, and add their names to the 'Leadership Distribution List' in [PSDCoP Email List](https://086gc.sharepoint.com/:x:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Pacific%20Salmon%20Data%20CoP/PSDCoP%20Email%20List.xlsx?d=wd8de377d03dc465bb7efe01c4bf8cc55&csf=1&web=1&e=1mI0zL)

There may be instances where the old WG word doc identifies sections, branches, or division that aren't represented in the invite spreadsheet. In those cases, just make sure the spreadsheet has the complete set (set union) of managers identified in both lists, even if there's no clear staff member to associate.

**Comment by stfinnis** [comment]
For reference, we save things related to the PSDCoP in the following places:

- The run of show (i.e., meeting agenda and planning notes) and contact list in the [DSU SharePoint](https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=m8V3Bn&CID=18254dd8%2D5c31%2D426f%2D8ed9%2Db05eb3f29970&FolderCTID=0x012000ABC2B68C9192E640A2DB54FAC2B05542&id=%2Fsites%2FFishery%2DAssessment%5FData%5FSection%2DDataStewardshipUnit2%2FShared%20Documents%2FData%20Stewardship%20Unit%2FPacific%20Salmon%20Data%20CoP&viewid=fcab37e5%2D35f1%2D49de%2Da29c%2Dc863f611adca)
- Meeting notes, presentations and anything else all PSDCoP members should have access to on the [PSDCoP SharePoint](https://086gc.sharepoint.com/sites/PacificRegionDataCommunity-PacificSalmonDataCommunityofPracticePSDCoP).
