### ISSUE TITLE
Create an Intranet Sharepoint site to communicate DSU initiatives and provide engagement pathway for Pacific Region

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#20]

**Comment by stfinnis** [comment]
An initial internal [DSU SharePoint ](https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section/SitePages/Data%20Stewardship%20Unit%20Page.aspx) has been developed and published on the FADS site. We will continue to add to this over time. The page has been made public to all members of DFO.

**Comment by stfinnis** [comment]
The SharePoint has been created and we will add content over time. 
We still need to address access issues (people need to request access to view the site). @Br-Johnson, can you try adding me as an admin so I can test this out? Thanks!

**Comment by AnnaD-M** [comment]
@stfinnis when we met with Peter on Friday, we discussed the possibility of having the DSU SharePoint site live on the Pacific Region Data Community site to bypass the access issues, but Peter has to get approval from his team...

**Comment by Br-Johnson** [comment]
Peter also mentioned that not a lot of people use the Pacific Region Data Community site based on the analytics.

We also discussed the possibility of having an Intranet site and working with Comms team. Seems like a long road.

**Comment by Br-Johnson** [comment]
Decided for now to keep the SharePoint site as it is. But transfer content to a GitHub page given the issues with access in SharePoint.
