### ISSUE TITLE
Develop a survey to gauge user satisfaction with data stewardship processes and gather feedback for targeted support

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#23]
- Microsoft Forms is limited
- Survey123: if kept to browser version only, anyone with a DFO email can access the survey (must be connected to VPN). To make public, provide entire form folder to CDOS (IT).

**Comment by AnnaD-M** [comment]
Update:

- Confirmed that survey created in Survey123 is only viewable when working on the DFO network/connected to the VPN.
- [Working version of Survey](https://survey123.arcgis.com/share/2b28b61fa73948eeb928e6985c9e6706?portalUrl=https://gisd.dfo-mpo.gc.ca/portal)
- Survey should be short, ~5 questions. Majority should be likert scale with option to add additional comments. At least one question should be an open-ended/freeform question.
- @AnnaD-M and @stfinnis to come up with 5 questions separately, then come together to make decisions about final questions. [SharePoint Word Doc](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Pacific%20Salmon%20Data%20CoP/Pacific%20Salmon%20Data%20Community%20of%20Practice.docx?d=wc6615d2e8cf04283bf9b5a3836f6f1cf&csf=1&web=1&e=pBQPrw)

**Comment by AnnaD-M** [comment]
Anna's draft questions added to [SharePoint Word Doc](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Pacific%20Salmon%20Data%20CoP/Pacific%20Salmon%20Data%20Community%20of%20Practice.docx?d=wc6615d2e8cf04283bf9b5a3836f6f1cf&csf=1&web=1&e=pBQPrw)

**Comment by ShaorongDFO** [comment]
I’d like to share some of my experiences for the survey. Having spent 25 years in the MGL lab, I’ve been deeply involved as a data producer, setting up databases and managing them in collaboration with external teams. My experience includes handling large datasets from projects involving microarrays, qPCR, FitChip, eDNA, etc.
One of the biggest challenges we faced was securing adequate funding from DFO, not just for database management, but also for sufficient storage space (now cloud-based), and hiring skilled programmers to build and maintain the database systems. It’s promising that PSSI has now made data literacy and database management centralization a priority.
Another recurring issue has been that DFO often hires skilled programmers or data analysts at the BI-02 or EG-05 level, but the salary is insufficient to retain them long-term. Additionally, IT restrictions have posed significant obstacles. Having a dedicated IT team to support each lab’s data management would be a real breakthrough.
I hope these insights can contribute to our discussions as we move forward with the survey.

**Comment by AnnaD-M** [comment]
Thank you for this valuable feedback @ShaorongDFO, I've updated the [survey document notes](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/_layouts/15/Doc.aspx?sourcedoc=%7BC6615D2E-8CF0-4283-BF9B-5A3836F6F1CF%7D&file=Pacific%20Salmon%20Data%20Community%20of%20Practice.docx&action=default&mobileredirect=true) to include:

SHAORONG’S KEY CHALLENGES – TO INCORPORATE 
- Securing adequate funding for storage space 
- Securing adequate funding for hiring and retaining skilled programmers or data analysts 
- Securing adequate funding for ongoing database maintenance and upgrades 
- Lack of dedicated IT support 
- Restricted to using DFO-sanctioned and IT-supported software that prevents the adoption of newer, more efficient tools and practices 

Feel free to add to or edit in the document. Hoping to incorporate this input and perhaps thin out the options for the question 'What challenges do you face in managing your data throughout its lifecycle?'

**Comment by Br-Johnson** [comment]
Hey @AnnaD-M @stfinnis did you guys come up with a final set of questions? Just read through the doc and wondered whether you came to a resolution or if you are waiting for some input from me.

**Comment by AnnaD-M** [comment]
@Br-Johnson it's on my list to go through our V2 and have something for you to review. Will aim to have it done by the end of the week.
