### ISSUE TITLE
Conduct a Stakeholder Analysis for the Pacific Salmon Data Community

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#24]
[Here's a link to the current doc](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Project%20Mgmt/DSU%20Stakeholder%20Analysis%20and%20Mapping.docx?d=wcc9c36519df8437693c725128077f8c8&csf=1&web=1&e=vfKCda)

The goal is for everyone to just build up their understanding of who the key players are that we need to work with. Doesn't need to be a formal word-smithed doc to share. Internal only.

**Comment by Br-Johnson** [comment]
@stfinnis @ShaorongDFO 

Shaorong indicated she is keen to understand who is responsible for what databases and get a high-level picture of who all the key players are.  Can the two of you work together to make sure efforts are aligned? Not sure what kind of output you want to produce, but just consolidating different outputs into a Stakeholder document or folder would be a good start to make sure we're not reproducing efforts.

@AnnaD-M is also currently exploring different data inventories via #58 which will have some cross over with the effort to identify stakeholders. @AnnaD-M may also take more of an active role in establishing the Pacific Salmon Data Community of Practice. 

All that to say please all work together and coordinate outputs if you're thinking about listing out different stakeholders

**Comment by AnnaD-M** [comment]
New Stakeholder List in Excel format created: [DSU Stakeholder Link](https://086gc.sharepoint.com/:x:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Project%20Mgmt/DSU%20Stakeholder%20LIst.xlsx?d=w6494f172ce574a169589b625986d4ef7&csf=1&web=1&e=bwTf9S )

**Comment by AnnaD-M** [comment]
New Stakeholder List in Excel format created: [DSU Stakeholder List](https://086gc.sharepoint.com/:x:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Project%20Mgmt/DSU%20Stakeholder%20LIst.xlsx?d=w6494f172ce574a169589b625986d4ef7&csf=1&web=1&e=bwTf9S)

**Comment by AnnaD-M** [comment]
**Decision:** Stakeholder list will be transitioned to Power Apps in the near future

**Comment by AnnaD-M** [comment]
Contributions to the established stakeholder list are ongoing.
