### ISSUE TITLE
Identify, consolidate and prioritize un-managed salmon data sets for data stewardship unit support and engagement

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#36]
@AnnaD-M We're not quite at a place where we can do this yet. But what I would like to see is to be able to tag certain datasets in the PowerApps Data Inventory as being priority if they are associated with an upcoming FSAR (WCVI Chinook, Barkley Sockeye, Yukon Chinook)

**Comment by AnnaD-M** [comment]
@Br-Johnson I added a column to flag FSAR-associated data assets
#67
