### ISSUE TITLE
Update Commercial Salmon Catch Query to show mgmt_area as integer

### ISSUE THREAD

**Issue by AnnaD-M** [dfo-pacific-science/data-stewardship-unit#41]

**Comment by Br-Johnson** [comment]
@AnnaD-M At some point can you check into if we can specify this (and all other variable type assignments) in the DataFlow that copies the FOS LH into our workspace or somewhere further upstream so that all variable types are correct when brought in?

**Comment by AnnaD-M** [comment]
That is a really good point. I have asked Jason if mgmt_area is stored as text consistently in FOS, which he confirmed.

**Comment by Br-Johnson** [comment]
I noticed that all integers are stored as floating point decimal values once in the Lakehouse. You can also download SQL Developer from the Software Center yourself if you like and I can email you credentials to view FOS
