### ISSUE TITLE
Engage with Enterprise Data Hub (Platform and staff) for Publishing Data

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#48]
- [ ] Complete (all?) EDH Training Modules: https://086gc.sharepoint.com/sites/EDHCentreCentreCDE/SitePages/Training.aspx
- [ ] Schedule live virtual training with EDH Support Team
- [ ] Identify Key Stakeholders from EDH Team

**Comment by stfinnis** [comment]
Based on discussions throughout December, I will no longer be focusing on this work. I wrote up some [notes about open data/EDH submissions](https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/EDH%20and%20Open%20Data/Notes%20for%20improving%20submissions%20to%20Open%20Data.docx?web=1) in case we ever come back to this, or need these links in the future! I will close this issue.
@Br-Johnson, should Issues [37](https://github.com/orgs/dfo-pacific-science/projects/4/views/6?pane=issue&itemId=84708024&issue=dfo-pacific-science%7Cdata-stewardship-unit%7C37) and [39](https://github.com/orgs/dfo-pacific-science/projects/4/views/6?pane=issue&itemId=84708029&issue=dfo-pacific-science%7Cdata-stewardship-unit%7C39) also be closed? I believe they're duplicates.
