### ISSUE TITLE
Create a Business Process Model in Visio to identify an ideal process for the DSU to keep track of 'un-managed' (un-findable) data

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#59]
Here's a start: https://086gc.sharepoint.com/:u:/r/sites/PacificRegionDataCommunity-PacificSalmonDataCommunityofPracticePSDCoP/Shared%20Documents/FADS%20PSSI%201.1%20Projects%20-%20DRAFTS/PID%20Integrated%20Project%20and%20Data%20Inventory/miro%20board.url?csf=1&web=1&e=oHWU9F

**Comment by Br-Johnson** [comment]
Here's a draft done in the browser, not compliant with BPMN https://086gc-my.sharepoint.com/:u:/g/personal/brett_johnson_dfo-mpo_gc_ca/Efm_mHdoM9dKl1IAHdrI3kAB4UjxP1UpDeLfqAMAdWVJzw?e=7ZXtcc

**Comment by AnnaD-M** [comment]
[Link to updated draft, not compliant with BPMN](https://086gc.sharepoint.com/:u:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/_layouts/15/Doc.aspx?sourcedoc=%7B3CDF8531-BF69-4507-9356-E8BC433447C3%7D&file=DSU%20Data%20Inventory%20Flow.vsdx&action=edit&mobileredirect=true&or=PrevEdit)

- [x] Create hyperlinks from URLs once we have access to Visio desktop

**Comment by Br-Johnson** [comment]
First draft is created here: https://086gc.sharepoint.com/:u:/r/sites/PacificRegionDataCommunity-PacificSalmonDataCommunityofPracticePSDCoP/Shared%20Documents/FADS%20PSSI%201.1%20Projects%20-%20DRAFTS/PID%20Integrated%20Project%20and%20Data%20Inventory/miro%20board.url?csf=1&web=1&e=oHWU9F
