### ISSUE TITLE
Determine how to best support OCDS Data Stewardship Initiative

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#69]
Background notes on short-form assignment here:
https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/_layouts/OneNote.aspx?id=%2Fsites%2FFishery-Assessment_Data_Section-DataStewardshipUnit2%2FShared%20Documents%2FData%20Stewardship%20Unit%2FDATAREEF&wd=target%28Knowledge%20Base.one%7C263B988A-E92F-4665-9B37-2B0719C21948%2FData%20Stewardship%20Initiative%7C2B550D78-B1A0-4A05-9022-3D506AF29D92%2F%29
onenote:https://086gc.sharepoint.com/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/DATAREEF/Knowledge%20Base.one#Data%20Stewardship%20Initiative&section-id={263B988A-E92F-4665-9B37-2B0719C21948}&page-id={2B550D78-B1A0-4A05-9022-3D506AF29D92}&end

**Comment by Br-Johnson** [comment]
@stfinnis and @AnnaD-M when you get a chance over the next couple of weeks could you provide a couple of summary thoughts here on how best to proceed with supporting the OCDS DSI?

If you have any broader thoughts about the value or challenges related to the DSI that would be welcome too! We might want to consolidate some feedback to give Marisa and Declan.

One issue I see is the scalability of the short form given that almost everyone identifies themselves as a data steward and that people will tend to go down that path. I also have a feeling that assigning the Trustee (via MOU) is much more critical than the Steward. I also worry that assigning a Trustee at the level of Director or division manager is much too high for them to meaningfully meet their role and responsibility of being a trustee and supporting data stewards.

**Comment by stfinnis** [comment]
Declan Embury and I talked about this on Nov 22. Finally updating this now! 

Declan noted he doesn't need too much additional support from the DSU and there aren't pressing tasks that we can help with. However, he said it would be great if we could continue to answer any emails/questions we get about it. In particular, to make sure that people don't feel too worried about filling out all the data roles with someone's name. So, don't stress if there isn't someone currently doing a certain role (leave it blank).

He also said he discussed the issue of trustees to the Regional Data Committee (RDC) in October. He suggested the RDC be the Trustees when signing the MOUs. He said a lot of people felt nervous assigning someone like their Division Manager as the trustee, especially when they often don't know the specifics of the datasets. Declan's suggestion was approved RDC but an official announcement hasn't been made yet. There's more info on [Declan's PowerPoint](https://086gc.sharepoint.com/:p:/r/sites/StrategicDataPolicyandAnalytics/DocumentCenter/_layouts/15/Doc.aspx?sourcedoc=%7BA14A37F7-5DEF-4E4A-A2F0-B65536E5F5C0%7D&file=Approach%20to%20Data%20Trustees%20in%20the%20Region%20-%20Oct%20RDC.pptx&action=edit&mobileredirect=true), including which members make up the RDC: 

I think we shouldn't push to be overly-involved with the DSI. But there are probably ways we can use the info they're collecting to help teams with their data.

Declan and I will continue to meet monthly a few days after every RDC meeting to discuss issues/shared challenges.

**Comment by Br-Johnson** [comment]
Thank you Stephen! I will close this out based on the decision that the best way to support the OCDS with the DSI is for us to all have an understanding of it, answer questions from staff, and otherwise let Declan and the OCDS play the lead role in filling out short form assignments.
