### ISSUE TITLE
Create GitHub Pages site for DSU Content

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#72]
- [x] Brett push the skeleton quarto site to this repo
- [x] Incorporate the content Stephen wrote from our SharePoint site
- [x] Workshop visuals (color palette, logo, and other images)
- [x] Website draft
- [x] Ticket to IT for access to DFO org

**Comment by alburycatalina** [comment]
Interested in taking on this item!

**Comment by Br-Johnson** [comment]
Sounds good let's talk about it more in real time.

**Comment by alburycatalina** [comment]
- [x] HTML rendering issue with blank perspectives button (can someone review)?
- [x] Touchups to logo from feedback
- [x] Alter site color palette
- [x] Decide on site url (https://github.io/dfo-mpo/pac-sci-data-stewardship.com?)
- [x] Review of content
- [x] Add to resources page
- [x] Team page photos

**Comment by Br-Johnson** [comment]
Was thinking https://github.io/dfo-pacific/science-data-stewardship

The 'official' GitHub org administrated by CDOS is not a paid account so doesn't really offer us any advantages. This would require us to set up a new org called `dfo-pacific`

**Comment by Br-Johnson** [comment]
github.io/dfo-pacific-science/data-stewardship is better

**Comment by alburycatalina** [comment]
How about github.io/dfo-mpo/pacific-data-stewardship ? This would avoid us making a new org

**Comment by Br-Johnson** [comment]
I just set up https://github.com/dfo-pacific-science for regional coordination

**Comment by alburycatalina** [comment]
Great, not sure how I missed that! Repo is forked over there.

**Comment by alburycatalina** [comment]
- [x] Training resources section content
- [x] ~~Workshop dashboard vision~~ (table for now)

**Comment by alburycatalina** [comment]
@Br-Johnson version 1 is complete! After one more review, maybe we can share this?
