### ISSUE TITLE
Create a stakeholder engagement plan

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#76]
Can the three of you (@AnnaD-M @ShaorongDFO @stfinnis) coordinate a plan to engage stakeholders? Identify who you need to talk to, what information you need, and where you might be able to find the information (in our section) before reaching out to stakeholders. Think about a shared place to keep engagement notes/results for us to communicate within the DSU and FADS. Goals are: 1) to make sure we're taking full advantage of the knowledge in our section and the resources they have access to; 2) Avoid burnout from stakeholders being engaged regarding the same topic more than once; 3) Prioritize engagements as they relate to priority data products.

Please have a first draft of the doc completed before Thursday October 10th. We will all be receiving a briefing from one of our colleagues in CDOS on Friday who will give us an overview of the engagement work they've done as it relates to NuSEDs. Erika and Tom will also come to that briefing. 

Please share the doc with us before the call, and we will help finalize it and fill in the gaps.

We should think about strategies for sharing engagement results and managing our shared knowledge within FADS

**Comment by ShaorongDFO** [comment]
I created a new folder in our [SharePoint](https://086gc.sharepoint.com/:f:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Stakeholder%20Engagement%20Info?csf=1&web=1&e=57M7XY)  called "Stakeholder Engagement Info". I also made each of us a folder under it. I'm going to move all my engagement note/results in my folder. I also use ChatGPT generated a document [Stakeholder Engagement Plan Template_Oct2024](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Stakeholder%20Engagement%20Info/Stakeholder%20Engagement%20Plan%20Template_Oct2024.docx?d=w2ae74b41eecb425e8c50b644975881d8&csf=1&web=1&e=l8wf18) as a place holder. We can start working on that next Monday.

**Comment by AnnaD-M** [comment]
The team made updates to the [Stakeholder Engagement Plan Template_Oct2024](https://086gc.sharepoint.com/:w:/r/sites/Fishery-Assessment_Data_Section-DataStewardshipUnit2/Shared%20Documents/Data%20Stewardship%20Unit/Stakeholder%20Engagement%20Info/Stakeholder%20Engagement%20Plan%20Template_Oct2024.docx?d=w2ae74b41eecb425e8c50b644975881d8&csf=1&web=1&e=l8wf18)
