### ISSUE TITLE
Determine how the DM Apps Science Project Planning Tool can be leveraged for salmon data

### ISSUE THREAD

**Issue by AnnaD-M** [dfo-pacific-science/data-stewardship-unit#82]
[Science Project Planning Tool](https://dmapps/en/ppt/)

Basic info:

- Tool for the tracking, development and coordination of science project workplans.
- Being used by Cory Lagasse to enter information about PSSI-funded projects.
- Built on the same framework developed by David Fishman for the [Project Publications Inventory](https://dmapps/en/publications/)
- Tied to #58 and #80 

Useful links from Cory:

- [Airtable of the Pacific Salmon Information Management System (Read-only)](https://airtable.com/appXE8Ew1kvx559Fd/shrYDQposATHEEEPj)
- [Pacific Salmon IMS PowerPoint presentation](https://086gc-my.sharepoint.com/:p:/r/personal/cory_lagasse_dfo-mpo_gc_ca/_layouts/15/Doc.aspx?sourcedoc=%7BC0667A59-E343-4CBD-B78E-68FDBB834730%7D&file=INTRO%20-%20Pacific%20Salmon%20IMS.pptx&action=edit&mobileredirect=true)

To do:

- [x] #86
- [ ] Identify and inventory data products from PSSI-funded projects
- [ ] Follow up on projects where PIs identified that data management support was needed, or cases where data is being stored on local hard drives. Work with these researchers to improve access and findability.
- [ ] #105
- [ ] Look into how to clearly define the expectations for data projects produced from PSSI-funded initiatives. Follow up on projects that do not have a Data Management Agreement in the PPT.
- [ ] At a later stage, inventory data products (minimum metadata) on EDH?

**Comment by AnnaD-M** [comment]
**Viewing relevant projects:**
Filtering to draw out salmon related projects in the Pacific region (then focus in on juvenile salmon and salmon biodata):
Region: Pacific
OM Cost Funding Source: PSSI (B-base)
Project tags/keywords: e.g., PSSI 1.1, PSSI 9/10

= 131 projects, with duplication of funding years

**Data & Data Product Inventorying**
PSSI-funded projects are required to create a project entry. Before receiving funding for 2024/25, must prove the previous year priorities have been met. How to increase accountability for data management/abiding by FAIR principles? Ask Amelia if it is possible to use the form to verify/report what data has been collected, what data products have been produced, the actual storage location (may be different from planned storage), how to and who has access. Make this a requirement for receiving 2024/5 funding, as the process to collect this information adds to workload and may take months to collect...

**Comment by AnnaD-M** [comment]
**Update:** Action items added above after meeting with Cory Lagasse to discuss PSSI and FADS coordination on project and data management.

**Comment by Br-Johnson** [comment]
Closing this one out since the major items listed here that for sure need doing have been transformed into separate issues. Otherwise, the main thrust of this issue was deciding how the DM Apps Science Project Planning Tool would be used by DSU, and we've decided that we will not use it directly but pull information from it and other inventories to create an integrated view (#80)
