### ISSUE TITLE
Test and Validate Commercial Openings Query

### ISSUE THREAD

**Issue by AnnaD-M** [dfo-pacific-science/data-stewardship-unit#83]
- [ ] Add stat week?
- [ ] Filter target species field. OPENING_SPECIES.OPNSPC_TARGET_IND. Binary (target = 1).
- [ ] look into target species groupings. Jason has manually added this previously. Replicated target species in Power BI but currently not accounting for duplicate joins (e.g., OPNG_ID 66774 is for ‘CN, CO, PK’ only accounting for CK (OPENING_SPECIES.SPECIES_SPECIES_CDE). Note Area F North Coast Troll fishery FOS template has ‘CN’ instead of ‘CK’.
- [ ] add pfma subarea details field (source table unknown) – confirm if this is important detail to retain?
- [ ] Cast opening_ID as integer in notebook
- [ ] create text field duplicate of opening_ID (opening_ID_str) in notebook so that ‘Text Filter’ visual can be used to search for openings
- [ ] create start_date and end_date fields (same as start_time and end_time but without time) so that these fields can be used in the PV Opening Lookup.

**Comment by alburycatalina** [comment]
Revisit after Sherry has finished rewriting queries
