### ISSUE TITLE
Access to the Azure DevOps repo

### ISSUE THREAD

**Issue by alburycatalina** [dfo-pacific-science/data-stewardship-unit#86]

**Comment by Br-Johnson** [comment]
Getting access to these repo's seems to have a lot of red tape. Not sure who we will have to contact to get access. Also, this is not an immediate priority. Let's circle back to this once we've better scoped the Project/Data Inventory integration infrastructure.

**Comment by alburycatalina** [comment]
Will circle back after more progress on the data inventory
