### ISSUE TITLE
Research different platforms for creating and hosting controlled vocabularies

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#9]
Current thinking involves:

starting with a standard spreadsheet format for a data dictionary that includes definition, as well as relationships to other terms (narrower than, broader than, synonyms)
Process with python script, transforming to OWL or SKOS format
publish terms to w3id URIs for persistence and FAIRness
Integrate into DFO salmon Ontology
Integrate with NCEAS Salmon Domain ontolog

**Comment by Scott-Akenhead** [comment]
[Protoge](https://protege.stanford.edu/ )

**Comment by Br-Johnson** [comment]
Current thinking involves: 
- starting with a standard spreadsheet format for a data dictionary that includes definition, as well as relationships to other terms (narrower than, broader than, synonyms)
- Process with python script, transforming to OWL or SKOS format
- publish terms to w3id URIs for persistence and FAIRness
- Integrate into DFO salmon Ontology
- Integrate with NCEAS Salmon Domain ontology

**Comment by Br-Johnson** [comment]
- w3id for hosting terms
- LinkML .yaml files for creating data dictionary terms that can be turned into RDF easily
- RDF/SKOS/OWL format
- LinkML for publishing web page of terms using MKDocs
