### ISSUE TITLE
Transfer FOS project out of Pacific Science Sandbox into dedicated workspace

### ISSUE THREAD

**Issue by Br-Johnson** [dfo-pacific-science/data-stewardship-unit#91]
I reached out to Eric Quan and he is making the request directly to CDOS for a new workspace specifically for the FOS Data Explorer

**Comment by Br-Johnson** [comment]
@AnnaD-M @alburycatalina Eric Quan set up 3 new workspaces for FOS. Dev, Test, and Production. He also set up a pipeline between them that will allow us to update things and tinker before publishing to Production. Not sure we need three, probably two might have been fine. This is not the same as medallion architecture which focuses on different data quality levels, but is aimed at an effective deployment process that doesn't introduce bugs into production and avoids affecting users who are currently using the production app. I will add you both now to all three workspaces.

@alburycatalina good chance for you to look at how you think this should all work and discuss with Anna.

**Comment by alburycatalina** [comment]
Thanks for adding us. Is Sherry aware of the new workspaces? Are the changes she's currently making going to go into the test workspace?

**Comment by AnnaD-M** [comment]
Update: waiting for Sherry to complete her QA/QC of the commercial catch query before transitioning to a new workspace

**Comment by alburycatalina** [comment]
From the email chains with Sherry, this seems complete. Are there any outstanding steps to be taken @AnnaD-M?

**Comment by AnnaD-M** [comment]
It is not yet complete... Need to wait until Sherry has finished her QA/QC process so that the notebook can be replicated in the dedicated workspace. And also need to wait until Sherry has set up the data update schedule properly which I am meeting with her on Monday to go over.

**Comment by alburycatalina** [comment]
Awesome, thank you! Can I join on Monday to listen in?

**Comment by AnnaD-M** [comment]
Sure, it is just to go over the steps that I outlined in my email to her. She may not have access to the workspace that Joey set up the shortcut capability for. Backup plan was to ask for her to enable shortcuts on the lakehouse she has control over but hoping that I can help her tidy things up on their side. Can also ask her for an update on where the script is at and confirm whether it is just for commercial catch or it will encompass openings and vessel activity also. I'm hoping it is the combination!

**Comment by AnnaD-M** [comment]
@alburycatalina the meeting is on Tuesday, not Monday!

**Comment by AnnaD-M** [comment]
Set up in Fishery Operations System - Dev workspace
